# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iui47AfyU6ugnlonmE0jrZhod_q4z4rM
"""

def chatbot():
    print("ChatBot: Hello! Type 'exit' to quit.")
    while True:
        user_input = input("You: ").lower()

        if "hello" in user_input:
            print("ChatBot: Hi!")
        elif "how are you" in user_input:
            print("ChatBot: I'm fine, thanks!")
        elif "bye" in user_input or "exit" in user_input:
            print("ChatBot: Goodbye!")
            break
        else:
            print("ChatBot: Sorry, I don't understand.")

chatbot()